### ISSUE TITLE
Fails to build on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by KarthiAru** [jupyterlab-contrib/jupyterlab-variableInspector#232]
```
(dl4cv) ➜  Documents jupyter labextension install jupyterlab_variableinspector
Building jupyterlab assets (production, minimized)
An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-d0g_vx1z.log
```

**Error Log**
```
Node v16.13.0
Yarn configuration loaded.
 /usr/bin/npm pack jupyterlab_variableinspector
npm notice 
npm notice package: jupyterlab_variableinspector@0.3.0
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                   
npm notice 2.0kB  README.md                 
npm notice 2.8kB  lib/handler.d.ts          
npm notice 8.5kB  lib/handler.js            
npm notice 184B   lib/index.d.ts            
npm notice 10.2kB lib/index.js              
npm notice 520B   lib/inspectorscripts.d.ts 
npm notice 10.4kB lib/inspectorscripts.js   
npm notice 1.4kB  lib/kernelconnector.d.ts  
npm notice 2.0kB  lib/kernelconnector.js    
npm notice 1.2kB  lib/manager.d.ts          
npm notice 1.8kB  lib/manager.js            
npm notice 1.9kB  lib/variableinspector.d.ts
npm notice 5.4kB  lib/variableinspector.js  
npm notice 1.3kB  package.json              
npm notice 1.3kB  style/index.css           
npm notice === Tarball Details === 
npm notice name:          jupyterlab_variableinspector            
npm notice version:       0.3.0                                   
npm notice filename:      jupyterlab_variableinspector-0.3.0.tgz  
npm notice package size:  12.0 kB                                 
npm notice unpacked size: 52.0 kB                                 
npm notice shasum:        0a73c630ca331492c92d440dcb76e396d4a5c0ad
npm notice integrity:     sha512-3YJGFiz6BIxXw[...]YmnT56/tMD0Ew==
npm notice total files:   16                                      
npm notice 
jupyterlab_variableinspector-0.3.0.tgz
Node v16.13.0
Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.51.3: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.51.3: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.1" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.11.1" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.1.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
success Saved lockfile.
Done in 48.56s.
> node /home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> node /home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.1" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.11.1" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.1.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
Done in 1.84s.
> node /home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
assets by status 11 MiB [cached] 124 assets
orphan modules 5.02 MiB [orphan] 1291 modules
runtime modules 110 KiB 14 modules
built modules 15.4 MiB (javascript) 4.72 KiB (consume-shared) 4.68 KiB (share-init) [built]
  modules by path ./node_modules/ 15.4 MiB
    javascript modules 15.3 MiB 1076 modules
    json modules 33.2 KiB 6 modules
  consume-shared-module modules 4.72 KiB
    modules by path consume shared module (default) @jupyterlab/ 3.65 KiB 42 modules
    modules by path consume shared module (default) @lumino/ 588 bytes 14 modules
  provide-module modules 4.68 KiB 114 modules
  modules by path ./build/ 24.1 KiB
    ./build/bootstrap.js 3.86 KiB [built] [code generated]
    ./build/index.out.js + 1 modules 20.2 KiB [built] [code generated]
ERROR in resolving fallback for shared module @lckr/jupyterlab_variableinspector
Module not found: Error: Can't resolve '@lckr/jupyterlab_variableinspector' in '/home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/build'
resolve '@lckr/jupyterlab_variableinspector' in '/home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/build'
  Parsed request is a module
  using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/build/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/build/node_modules doesn't exist or is not a directory
      looking for modules in /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules
        single file module
          using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@lckr/jupyterlab_variableinspector)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.wasm doesn't exist
        existing directory /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector
          using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/package.json (relative path: .)
            using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@lckr/jupyterlab_variableinspector)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector is not a file
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector.wasm doesn't exist
              as directory
                existing directory /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector
                  using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/package.json (relative path: .)
                    use ./lib/index.js from main in package.json
                      using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/package.json (relative path: ./lib/index.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/lib/index.js doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/lib/index.js.js doesn't exist
                        .json
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/lib/index.js.json doesn't exist
                        .wasm
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/lib/index.js.wasm doesn't exist
                        as directory
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/lib/index.js doesn't exist
                    using path: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/index
                      using description file: /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/package.json (relative path: ./index)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/index doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/index.js doesn't exist
                        .json
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/index.json doesn't exist
                        .wasm
                          Field 'browser' doesn't contain a valid alias configuration
                          /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/staging/node_modules/@lckr/jupyterlab_variableinspector/index.wasm doesn't exist
      /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /home/karthik/.local/bin/.virtualenvs/dl4cv/share/jupyter/node_modules doesn't exist or is not a directory
      /home/karthik/.local/bin/.virtualenvs/dl4cv/share/node_modules doesn't exist or is not a directory
      /home/karthik/.local/bin/.virtualenvs/dl4cv/node_modules doesn't exist or is not a directory
      /home/karthik/.local/bin/.virtualenvs/node_modules doesn't exist or is not a directory
      /home/karthik/.local/bin/node_modules doesn't exist or is not a directory
      /home/karthik/.local/node_modules doesn't exist or is not a directory
      /home/karthik/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
webpack 5.64.1 compiled with 1 error and 109 warnings in 16856 ms
asset index.css 15.8 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 15.8 KiB = index.css 15.8 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 472 bytes [code generated]
webpack 5.64.1 compiled successfully in 891 ms
asset index.css 14.7 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 14.7 KiB = index.css 14.7 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-light-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/theme.css 472 bytes [code generated]
webpack 5.64.1 compiled successfully in 887 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
JupyterLab failed to build
Traceback (most recent call last):
  File "/home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield
  File "/home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 140, in start
    build(clean_staging=self.should_clean,
  File "/home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,
  File "/home/karthik/.local/bin/.virtualenvs/dl4cv/lib/python3.8/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)
RuntimeError: JupyterLab failed to build
Exiting application: lab
```

**Comment by jtpio** [comment]
> Installing with pip: `pip install lckr-jupyterlab-variableinspector`

Yes if you are using JupyterLab 3 you should install the extension with `pip`. It will be easier and normally you don't to rebuild JupyterLab afterwards anymore.

**Comment by fcollonval** [comment]
Closing as answered
